/**
 * Created for storing text in diffrent langages to support multi languages
 *
 * @format
 */

import LocalizedStrings from "react-native-localization";

export default new LocalizedStrings({
  en: {
    InternetError: "Please check internet connection!",
    designMaster:"Design Master",
    designList:"Design List",
    sizeMaster:"Size Master",
    sizeList:"Size List",
    sizeRangeMaster:"Size Range Master",
    sizeRangeList:"Size Range List",
    cuttingMaster:"Cutting Master",
    cuttingList:"Cutting List",
    orderMaster:"Order Master",
    code:"Code",
    enterCode:"Enter code",
    codeError:"Please enter code number!",
    name:"Name",
    enterName:"Enter name",
    nameError:"Please enter name!",
    color:"Color",
    enterColor:"Enter color",
    colorError:"Please enter color!",
    status:"Status",
    submit:"Submit",
    srNo:"Sr. No.",
    add:"Add",
    import:"Import",
    size:"Size",
    selectSize:"Select Size",
    range:"Range",
    selectedRange:"Selected Range",
    design:"Design",
    designNo:"Design No.",
    enterDesignNo:"Enter design number",
    designNoError:"Please enter design number",
    set:"Set",
    selectSet:"Select Set",
    remarks:"Remarks",
    enterRemark:"Enter remarks",
    remarkError:"Please enter remarks!",
    date:"Date",
    selectDate:"Select Date",
    gstNo:"GST No.",
    enterGst:"Enter GST No.",
    gstNoError:"Please enter GST Number!",
    reference:"Reference",
    enterReference:"Enter reference",
    referenceError:"Please enter reference",
    orderDate:"Order Date",
    quantity:"Quantity",
    addMore:"Add More",
    addOrder:"Add Order",
    selectDesign:"Select Design",
    selectedDesignDetails:"Selected Design Details",
    selectSize:"Select Size",
    qty:"Quantity",
    enterQty:"Enter Quantity",
    sizeRange:"Size range",
    selectSizeRange:"Select size range",
    price:"Price",
    enterPrice: "Enter price",
    noOfPc:"Number of pieces",
    enterNoOfPc:"Enter number of pieces",
    noOfPcError:"Please enter number of pieces",
    pcInRange:"Pieces in range",
    designedBy:"Designed by/Producer",
    enterDesignedBy:"Enter designed by/Producer",
    designedByError:"Please enter designed by/Producer",
    total:"Total",
    orderTotal:"Order Total",
    update:"Update",
    designPic:"Design Photo",
    customerName:"Customer Name",
    enterCustomerName:"Enter customer name",
    customerNameError:"Please enter customer name!",
    enterFname:"Enter first name",
    enterLname:"Enter last name",
    enterUsername:"Enter user name",
    enterPassword:"Enter password",

    cancel: "Cancel",
    ok:"OK",

    addDesignSuccess:"Design added successfully!",
    updateDesignSuccess:"Design updated successfully!",
    deleteDesignTitle:"Delete Design",
    deleteDesignMsg:"Are you sure want to delete this design?",

    addCuttingSuccess:"Cutting added successfully!",
    updateCuttingSuccess:"Cutting updated successfully!",
    deleteCuttingTitle:"Delete Cutting",
    deleteCuttingMsg:"Are you sure want to delete this cutting?",

    addSizeRangeSuccess:"Size range added successfully!",
    updateSizeRangeSuccess:"Size range updated successfully!",
    deleteSizeRangeTitle:"Delete SizeRange",
    deleteSizeRangeMsg:"Are you sure want to delete this sizeRange?",

    addOrderSuccess:"Order added successfully!",
    updateOrderSuccess:"Order updated successfully!",
    deleteOrderTitle:"Delete Order",
    deleteOrderMsg:"Are you sure want to delete this order?",
  },
});
